# Deploy the web application
# into the vercel as production
#
# ***** NOTE ******
# This deployment need to setup some secrets

name: Deploy Studio Application to Production

# define the env for this workflows
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_STUDIO_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STUDIO_PROJECT_ID }}

# Oonly run this workflows if
# the user start manual the actions
# and push the code into the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/studio/**"

jobs:
  update:
    name: Update Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Nodejs Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        working-directory: ./apps/studio
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./apps/studio
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ./apps/studio
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./apps/studio
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
